###
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: build markdown to PDF
  image: plass/mdtopdf
  commands:
  - mdtopdf /drone/src/README.md
  - ls /drone/src/
  when:
    branch:
    - master
