###
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: build markdown to PDF
  image: plass/mdtopdf
  volumes:
  - name: pdffile
    path: /drone/src/output
  commands:
  - mv /drone/src/README.md /drone/src/output
  - mdtopdf /drone/src/output/README.md

- name: publish a release
  image: plugins/github-release
  volumes:
  - name: pdffile
    path: /drone/src/output
  settings:
    api_key:
      from_secret: api_key
    draft: true
    files:
      - /drone/src/output/README.pdf
    title: ${DRONE_TAG}
  
volumes:
- name: pdffile
  temp: {}

trigger:
  event:
  - tag
