###
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: build markdown to PDF
  image: plass/mdtopdf
  commands:
  - w-mdtopdf /drone/src/INPUT.md
  when:
    branch:
    - master